
# 쓸모 있는 mutator

setSuitRank 함수에서 suit와 rank중 하나라도 값이 범위를 넘는 경우는 변경하지 않고 exception 처리를 하도록 수정하라.  (출력 메시지: "Error")

실행 예:
$ a.out
0 0
♠A
4 4
Error
1 12
♡K
1 13
Error
^d
$

Hint: while문 안에 try-catch를 넣어야 오류 후에도 반복이 된다.

```
#include <iostream>
using namespace std;
//enum suit { spade, heart, diamond, club };
char msg[] = "Error";
class Card{
private:
	const string suitname[4] = {"♠","♡","◇","♣"};
	const string rankname[13]={"A","2","3","4", "5","6","7","8","9","10", "J","Q","K"};
	short suit_, rank_;
public:
	void show(){
		cout << suitname[suit_]  << rankname[rank_] << endl;
	}
	// setSuitRank함수를 여기에...
	// 만일 suit나 rank 가 범위를 벗어나면 throw
	int setSuitRank(int suit, int rank){
		if (suit < 0 || suit > 3 || rank < 0 || rank > 12){
			throw(msg);
		}
		suit_ = suit;
		rank_ = rank;
	}
};


int main(){
	Card myCard;
	short suit, rank;
	 
	while ( cin >> suit >> rank ){
		try{
		myCard.setSuitRank(suit, rank);  // try-catch로 둘러싼다.
		myCard.show();
		} catch ( const char *a){
			cout<<a<<endl;
		}
	}
}

```
